// Generated by CoffeeScript 1.5.0
(function() {
  var ar, should;

  should = require("should");

  ar = require("../arity");

  describe('ar', function() {
    it('catches too many parameters', function() {
      var obj;
      obj = {
        func: ar(function() {})
      };
      return (function() {
        return obj.func("param1");
      }).should["throw"]();
    });
    it('catches too few parameters', function() {
      var obj;
      obj = {
        func: ar(function(a, b) {})
      };
      return (function() {
        return obj.func();
      }).should["throw"]();
    });
    it('mentions the parameters when throwing an error', function() {
      var obj;
      obj = {
        func: ar(function(a, b) {})
      };
      return (function() {
        return obj.func();
      }).should["throw"](/.*a, b.*/);
    });
    it('mentions the function\'s name when throwing an error', function() {
      var obj;
      obj = {
        func: ar(function myFunc (a, b) { })
      };
      return (function() {
        return obj.func();
      }).should["throw"](/.*myFunc.*/);
    });
    return it('runs the function when the right number of parameters are passed in', function() {
      var obj;
      obj = {
        sum: ar(function(a, b) {
          return a + b;
        })
      };
      return obj.sum(2, 3).should.eql(5);
    });
  });

}).call(this);
